<div class="socialBox box-1">
  <div>
	  <div class="fb-like"  data-href="https://www.facebook.com/smartcitizenBCN" data-send="false" data-layout="button_count" data-width="100" data-show-faces="false"></div>
  </div>
  <div class="twitter">
	  <a href="https://twitter.com/share" class="twitter-share-button" data-url="twitter.com/fablabbcn" data-via="fablabbcn" data-hashtags="smartcitizen">Tweet</a>
  </div>
  <div class="google">
	  <div class="g-plusone" data-size="medium">
		  <g:plusone></g:plusone>
	  </div>
  </div>
</div>